# Generated by Django 5.1.1 on 2024-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default.jpg', upload_to='images/products/products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
